[build]

  functions = "build/functions"

  publish = "build"

 

[build.environment]

  NODE_ENV = "development"

  DB = "mongodb+srv://ln613:20191225@vttc-drvhn.mongodb.net/vttc?retryWrites=true"

  CLOUDINARY_KEY = "985763522939218"

  CLOUDINARY_SECRET = "S4C_8mZC_QvtqvgjOHkAa3hPw0k"

  ADMIN_USER = "vttc"

  ADMIN_PASSWORD = "Joe19651965"

  JWT_SECRET = "S4C_8mZC_QvtqvgjOHkAa3hPw0k"

  GITHUB_DB = "https://raw.githubusercontent.com/ln613/n2/master/data/"